-- ─────────────────────────────────────────────────────────────────────────────
-- 010_session_schedule.sql
-- Stores a pre-planned match schedule generated by the Session Scheduler.
-- Each row is one planned match (4 player IDs = 2 doubles pairs vs each other).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS session_schedule (
  id            UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id    UUID        NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  match_order   INT         NOT NULL,  -- 1-based display order
  -- Team 1 (pair A)
  t1_player1_id UUID        NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  t1_player2_id UUID        NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  -- Team 2 (pair B)
  t2_player1_id UUID        NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  t2_player2_id UUID        NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  -- Optional: which player sits out if an odd number of players are present
  -- (NULL when all players are playing in this match)
  sitting_out_player_id UUID REFERENCES players(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (session_id, match_order)
);

-- Allow anyone to read the schedule (non-admin viewers of session page)
ALTER TABLE session_schedule ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read session_schedule"
  ON session_schedule FOR SELECT
  USING (true);

CREATE POLICY "Authenticated can insert session_schedule"
  ON session_schedule FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Authenticated can delete session_schedule"
  ON session_schedule FOR DELETE
  USING (true);

-- Index for fast lookups by session
CREATE INDEX IF NOT EXISTS idx_session_schedule_session_id
  ON session_schedule (session_id, match_order);
